version: "3"
services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    ports:
      - "8080:8080"
  app:
    container_name: app
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    environment:
      - GOPATH=/go
    volumes:
      - ./go:/go/src/app/go
    command: go run main.go
    ports:
      - "8181:8181"
